#define ADDR_NPU_CODE           0x30ff0000
#define ADDR_NPU_CLEN           0x30ff0004
#define ADDR_NPU_RUN            0x30ff0008
#define ADDR_NPU_ELEN           0x30ff000c
#define ADDR_NPU_VER            0x30ff0010
#define ADDR_NPU_MACRO          0x30ff0014
#define ADDR_NPU_DMA            0x30ff0018
#define ADDR_NPU_DMAFT          0x30ff001c
#define ADDR_NPU_RDMA0_SRC0     0x30ff0020
#define ADDR_NPU_RDMA0_SRC1     0x30ff0024
#define ADDR_NPU_RDMA0_SRC2     0x30ff0028
#define ADDR_NPU_RDMA0_SRC3     0x30ff002c
#define ADDR_NPU_RDMA0_SRC4     0x30ff0030
#define ADDR_NPU_RDMA0_DST      0x30ff0034
#define ADDR_NPU_RDMA0_BLK0     0x30ff0038
#define ADDR_NPU_RDMA0_BLK1     0x30ff003c
#define ADDR_NPU_RDMA1_SRC0     0x30ff0040
#define ADDR_NPU_RDMA1_SRC1     0x30ff0044
#define ADDR_NPU_RDMA1_SRC2     0x30ff0048
#define ADDR_NPU_RDMA1_SRC3     0x30ff004c
#define ADDR_NPU_RDMA1_SRC4     0x30ff0050
#define ADDR_NPU_RDMA1_DST      0x30ff0054
#define ADDR_NPU_RDMA1_BLK0     0x30ff0058
#define ADDR_NPU_RDMA1_BLK1     0x30ff005c
#define ADDR_NPU_RDMA2_SRC0     0x30ff0060
#define ADDR_NPU_RDMA2_SRC1     0x30ff0064
#define ADDR_NPU_RDMA2_SRC2     0x30ff0068
#define ADDR_NPU_RDMA2_SRC3     0x30ff006c
#define ADDR_NPU_RDMA2_SRC4     0x30ff0070
#define ADDR_NPU_RDMA2_DST      0x30ff0074
#define ADDR_NPU_RDMA2_BLK0     0x30ff0078
#define ADDR_NPU_RDMA2_BLK1     0x30ff007c
#define ADDR_NPU_WDMA0_SRC      0x30ff0080
#define ADDR_NPU_WDMA0_DST0     0x30ff0084
#define ADDR_NPU_WDMA0_DST1     0x30ff0088
#define ADDR_NPU_WDMA0_DST2     0x30ff008c
#define ADDR_NPU_WDMA0_DST3     0x30ff0090
#define ADDR_NPU_WDMA0_DST4     0x30ff0094
#define ADDR_NPU_WDMA0_BLK0     0x30ff0098
#define ADDR_NPU_WDMA0_BLK1     0x30ff009c
#define ADDR_NPU_WDMA1_SRC      0x30ff00a0
#define ADDR_NPU_WDMA1_DST0     0x30ff00a4
#define ADDR_NPU_WDMA1_DST1     0x30ff00a8
#define ADDR_NPU_WDMA1_DST2     0x30ff00ac
#define ADDR_NPU_WDMA1_DST3     0x30ff00b0
#define ADDR_NPU_WDMA1_DST4     0x30ff00b4
#define ADDR_NPU_WDMA1_BLK0     0x30ff00b8
#define ADDR_NPU_WDMA1_BLK1     0x30ff00bc
#define ADDR_NPU_WDMA2_SRC      0x30ff00c0
#define ADDR_NPU_WDMA2_DST0     0x30ff00c4
#define ADDR_NPU_WDMA2_DST1     0x30ff00c8
#define ADDR_NPU_WDMA2_DST2     0x30ff00cc
#define ADDR_NPU_WDMA2_DST3     0x30ff00d0
#define ADDR_NPU_WDMA2_DST4     0x30ff00d4
#define ADDR_NPU_WDMA2_BLK0     0x30ff00d8
#define ADDR_NPU_WDMA2_BLK1     0x30ff00dc
#define ADDR_NPU_NMEM           0x30ff00e0
#define ADDR_NPU_NMEM_FM0       0x30ff00e4
#define ADDR_NPU_NMEM_FM1       0x30ff00e8
#define ADDR_NPU_NMEM_FM2       0x30ff00ec
#define ADDR_NPU_NMEM_PS0       0x30ff00f0
#define ADDR_NPU_NMEM_PS1       0x30ff00f4
#define ADDR_NPU_NMEM_PS2       0x30ff00f8
#define ADDR_NPU_NMEM_ST0       0x30ff00fc
#define ADDR_NPU_NMEM_ST1       0x30ff0100
#define ADDR_NPU_NMEM_ST2       0x30ff0104
#define ADDR_NPU_NMEM_PI0       0x30ff0108
#define ADDR_NPU_NMEM_PI1       0x30ff010c
#define ADDR_NPU_NMEM_PI2       0x30ff0110
#define ADDR_NPU_NMEM_PO0       0x30ff0114
#define ADDR_NPU_NMEM_PO1       0x30ff0118
#define ADDR_NPU_NMEM_PO2       0x30ff011c
#define ADDR_NPU_NMEM_RDMA0     0x30ff0120
#define ADDR_NPU_NMEM_RDMA1     0x30ff0124
#define ADDR_NPU_NMEM_RDMA2     0x30ff0128
#define ADDR_NPU_NMEM_WDMA0     0x30ff012c
#define ADDR_NPU_NMEM_WDMA1     0x30ff0130
#define ADDR_NPU_NMEM_WDMA2     0x30ff0134
#define ADDR_NPU_GETW0          0x30ff0138
#define ADDR_NPU_GETW1          0x30ff013c
#define ADDR_NPU_GETW2          0x30ff0140
#define ADDR_NPU_GETW3          0x30ff0144
#define ADDR_NPU_GETW           0x30ff0148
#define ADDR_NPU_CONV           0x30ff014c
#define ADDR_NPU_FMAP0          0x30ff0150
#define ADDR_NPU_FMAP1          0x30ff0154
#define ADDR_NPU_ZPAD           0x30ff0158
#define ADDR_NPU_IROW           0x30ff015c
#define ADDR_NPU_NEXT0          0x30ff0160
#define ADDR_NPU_NEXT1          0x30ff0164
#define ADDR_NPU_FMCROP         0x30ff0168
#define ADDR_NPU_FMOUT          0x30ff016c
#define ADDR_NPU_US             0x30ff0170
#define ADDR_NPU_HUS            0x30ff0174
#define ADDR_NPU_VUS            0x30ff0178
#define ADDR_NPU_PCONV          0x30ff017c
#define ADDR_NPU_TRIM           0x30ff0180
#define ADDR_NPU_GAP            0x30ff0184
#define ADDR_NPU_RELU           0x30ff0188
#define ADDR_NPU_RELU6          0x30ff018c
#define ADDR_NPU_PFUNC          0x30ff0190
#define ADDR_NPU_PFMAP0         0x30ff0194
#define ADDR_NPU_PFMAP1         0x30ff0198
#define ADDR_NPU_PZPAD          0x30ff019c
#define ADDR_NPU_PIROW          0x30ff01a0
#define ADDR_NPU_PNEXT0         0x30ff01a4
#define ADDR_NPU_PNEXT1         0x30ff01a8
#define ADDR_NPU_PFMCROP        0x30ff01ac
#define ADDR_NPU_PFMOUT         0x30ff01b0
#define ADDR_NPU_POOL           0x30ff01b4
#define ADDR_NPU_PAT            0x30ff01b8
#define ADDR_NPU_CC0            0x30ff01bc
#define ADDR_NPU_CC1            0x30ff01c0
#define ADDR_NPU_CC2            0x30ff01c4
#define ADDR_NPU_CC3            0x30ff01c8
#define ADDR_NPU_CC4            0x30ff01cc
#define ADDR_NPU_CC5            0x30ff01d0
#define ADDR_NPU_FORMAT         0x30ff01d4
#define ADDR_NPU_RESIZE         0x30ff01d8
#define ADDR_NPU_RESIZE_SRC     0x30ff01dc
#define ADDR_NPU_RESIZE_DST     0x30ff01e0
#define ADDR_NPU_RESIZE_INIT0    0x30ff01e4
#define ADDR_NPU_RESIZE_INIT1    0x30ff01e8
#define ADDR_NPU_RESIZE_RATIO0    0x30ff01ec
#define ADDR_NPU_RESIZE_RATIO1    0x30ff01f0
#define ADDR_NPU_CHAN           0x30ff01f4
#define ADDR_NPU_PREP0          0x30ff01f8
#define ADDR_NPU_PREP1          0x30ff01fc
#define ADDR_NPU_PREP2          0x30ff0200
#define ADDR_NPU_PREP3          0x30ff0204
#define ADDR_NPU_ENCRYPT        0x30ff0208
#define ADDR_NPU_KEY            0x30ff020c
#define ADDR_NPU_INTEN          0x30ff0210
#define ADDR_NPU_INT            0x30ff0214
#define ADDR_NPU_DBG0           0x30ff0218
#define ADDR_NPU_DBG1           0x30ff021c
#define ADDR_NPU_DBG2           0x30ff0220
#define ADDR_NPU_REGM           0x30ff0224
#define ADDR_NPU_DUMMY_0        0x30ff0228
#define ADDR_NPU_DUMMY_1        0x30ff022c
#define ADDR_NPU_DUMMY_2        0x30ff0230

#define VAL_ACL(x)    (((x)&0xffff))
#define VAL_ACH(x)    (((x)>>16)&0xffff)

#define ACL_NPU_MACRO       0xa
#define ACH_NPU_MACRO       0xb
#define ACL_NPU_DMAFT       0xe
#define ACH_NPU_DMAFT       0xf
#define ACL_NPU_RDMA0_SRC0  0x10
#define ACH_NPU_RDMA0_SRC0  0x11
#define ACL_NPU_RDMA0_SRC1  0x12
#define ACH_NPU_RDMA0_SRC1  0x13
#define ACL_NPU_RDMA0_SRC2  0x14
#define ACH_NPU_RDMA0_SRC2  0x15
#define ACL_NPU_RDMA0_SRC3  0x16
#define ACH_NPU_RDMA0_SRC3  0x17
#define ACL_NPU_RDMA0_SRC4  0x18
#define ACH_NPU_RDMA0_SRC4  0x19
#define ACL_NPU_RDMA0_DST   0x1a
#define ACH_NPU_RDMA0_DST   0x1b
#define ACL_NPU_RDMA0_BLK0  0x1c
#define ACH_NPU_RDMA0_BLK0  0x1d
#define ACL_NPU_RDMA0_BLK1  0x1e
#define ACH_NPU_RDMA0_BLK1  0x1f
#define ACL_NPU_RDMA1_SRC0  0x20
#define ACH_NPU_RDMA1_SRC0  0x21
#define ACL_NPU_RDMA1_SRC1  0x22
#define ACH_NPU_RDMA1_SRC1  0x23
#define ACL_NPU_RDMA1_SRC2  0x24
#define ACH_NPU_RDMA1_SRC2  0x25
#define ACL_NPU_RDMA1_SRC3  0x26
#define ACH_NPU_RDMA1_SRC3  0x27
#define ACL_NPU_RDMA1_SRC4  0x28
#define ACH_NPU_RDMA1_SRC4  0x29
#define ACL_NPU_RDMA1_DST   0x2a
#define ACH_NPU_RDMA1_DST   0x2b
#define ACL_NPU_RDMA1_BLK0  0x2c
#define ACH_NPU_RDMA1_BLK0  0x2d
#define ACL_NPU_RDMA1_BLK1  0x2e
#define ACH_NPU_RDMA1_BLK1  0x2f
#define ACL_NPU_RDMA2_SRC0  0x30
#define ACH_NPU_RDMA2_SRC0  0x31
#define ACL_NPU_RDMA2_SRC1  0x32
#define ACH_NPU_RDMA2_SRC1  0x33
#define ACL_NPU_RDMA2_SRC2  0x34
#define ACH_NPU_RDMA2_SRC2  0x35
#define ACL_NPU_RDMA2_SRC3  0x36
#define ACH_NPU_RDMA2_SRC3  0x37
#define ACL_NPU_RDMA2_SRC4  0x38
#define ACH_NPU_RDMA2_SRC4  0x39
#define ACL_NPU_RDMA2_DST   0x3a
#define ACH_NPU_RDMA2_DST   0x3b
#define ACL_NPU_RDMA2_BLK0  0x3c
#define ACH_NPU_RDMA2_BLK0  0x3d
#define ACL_NPU_RDMA2_BLK1  0x3e
#define ACH_NPU_RDMA2_BLK1  0x3f
#define ACL_NPU_WDMA0_SRC   0x40
#define ACH_NPU_WDMA0_SRC   0x41
#define ACL_NPU_WDMA0_DST0  0x42
#define ACH_NPU_WDMA0_DST0  0x43
#define ACL_NPU_WDMA0_DST1  0x44
#define ACH_NPU_WDMA0_DST1  0x45
#define ACL_NPU_WDMA0_DST2  0x46
#define ACH_NPU_WDMA0_DST2  0x47
#define ACL_NPU_WDMA0_DST3  0x48
#define ACH_NPU_WDMA0_DST3  0x49
#define ACL_NPU_WDMA0_DST4  0x4a
#define ACH_NPU_WDMA0_DST4  0x4b
#define ACL_NPU_WDMA0_BLK0  0x4c
#define ACH_NPU_WDMA0_BLK0  0x4d
#define ACL_NPU_WDMA0_BLK1  0x4e
#define ACH_NPU_WDMA0_BLK1  0x4f
#define ACL_NPU_WDMA1_SRC   0x50
#define ACH_NPU_WDMA1_SRC   0x51
#define ACL_NPU_WDMA1_DST0  0x52
#define ACH_NPU_WDMA1_DST0  0x53
#define ACL_NPU_WDMA1_DST1  0x54
#define ACH_NPU_WDMA1_DST1  0x55
#define ACL_NPU_WDMA1_DST2  0x56
#define ACH_NPU_WDMA1_DST2  0x57
#define ACL_NPU_WDMA1_DST3  0x58
#define ACH_NPU_WDMA1_DST3  0x59
#define ACL_NPU_WDMA1_DST4  0x5a
#define ACH_NPU_WDMA1_DST4  0x5b
#define ACL_NPU_WDMA1_BLK0  0x5c
#define ACH_NPU_WDMA1_BLK0  0x5d
#define ACL_NPU_WDMA1_BLK1  0x5e
#define ACH_NPU_WDMA1_BLK1  0x5f
#define ACL_NPU_WDMA2_SRC   0x60
#define ACH_NPU_WDMA2_SRC   0x61
#define ACL_NPU_WDMA2_DST0  0x62
#define ACH_NPU_WDMA2_DST0  0x63
#define ACL_NPU_WDMA2_DST1  0x64
#define ACH_NPU_WDMA2_DST1  0x65
#define ACL_NPU_WDMA2_DST2  0x66
#define ACH_NPU_WDMA2_DST2  0x67
#define ACL_NPU_WDMA2_DST3  0x68
#define ACH_NPU_WDMA2_DST3  0x69
#define ACL_NPU_WDMA2_DST4  0x6a
#define ACH_NPU_WDMA2_DST4  0x6b
#define ACL_NPU_WDMA2_BLK0  0x6c
#define ACH_NPU_WDMA2_BLK0  0x6d
#define ACL_NPU_WDMA2_BLK1  0x6e
#define ACH_NPU_WDMA2_BLK1  0x6f

#define ACL_NPU_NMEM_FM0    0x72
#define ACH_NPU_NMEM_FM0    0x73
#define ACL_NPU_NMEM_FM1    0x74
#define ACH_NPU_NMEM_FM1    0x75
#define ACL_NPU_NMEM_FM2    0x76
#define ACH_NPU_NMEM_FM2    0x77
#define ACL_NPU_NMEM_PS0    0x78
#define ACH_NPU_NMEM_PS0    0x79
#define ACL_NPU_NMEM_PS1    0x7a
#define ACH_NPU_NMEM_PS1    0x7b
#define ACL_NPU_NMEM_PS2    0x7c
#define ACH_NPU_NMEM_PS2    0x7d
#define ACL_NPU_NMEM_ST0    0x7e
#define ACH_NPU_NMEM_ST0    0x7f
#define ACL_NPU_NMEM_ST1    0x80
#define ACH_NPU_NMEM_ST1    0x81
#define ACL_NPU_NMEM_ST2    0x82
#define ACH_NPU_NMEM_ST2    0x83
#define ACL_NPU_NMEM_PI0    0x84
#define ACH_NPU_NMEM_PI0    0x85
#define ACL_NPU_NMEM_PI1    0x86
#define ACH_NPU_NMEM_PI1    0x87
#define ACL_NPU_NMEM_PI2    0x88
#define ACH_NPU_NMEM_PI2    0x89
#define ACL_NPU_NMEM_PO0    0x8a
#define ACH_NPU_NMEM_PO0    0x8b
#define ACL_NPU_NMEM_PO1    0x8c
#define ACH_NPU_NMEM_PO1    0x8d
#define ACL_NPU_NMEM_PO2    0x8e
#define ACH_NPU_NMEM_PO2    0x8f
#define ACL_NPU_NMEM_RDMA0  0x90
#define ACH_NPU_NMEM_RDMA0  0x91
#define ACL_NPU_NMEM_RDMA1  0x92
#define ACH_NPU_NMEM_RDMA1  0x93
#define ACL_NPU_NMEM_RDMA2  0x94
#define ACH_NPU_NMEM_RDMA2  0x95
#define ACL_NPU_NMEM_WDMA0  0x96
#define ACH_NPU_NMEM_WDMA0  0x97
#define ACL_NPU_NMEM_WDMA1  0x98
#define ACH_NPU_NMEM_WDMA1  0x99
#define ACL_NPU_NMEM_WDMA2  0x9a
#define ACH_NPU_NMEM_WDMA2  0x9b
#define ACL_NPU_GETW0       0x9c
#define ACH_NPU_GETW0       0x9d
#define ACL_NPU_GETW1       0x9e
#define ACH_NPU_GETW1       0x9f
#define ACL_NPU_GETW2       0xa0
#define ACH_NPU_GETW2       0xa1
#define ACL_NPU_GETW3       0xa2
#define ACH_NPU_GETW3       0xa3
#define ACL_NPU_GETW        0xa4
#define ACH_NPU_GETW        0xa5

#define ACL_NPU_CONV        0xa6
#define ACH_NPU_CONV        0xa7
#define ACL_NPU_FMAP0       0xa8
#define ACH_NPU_FMAP0       0xa9
#define ACL_NPU_FMAP1       0xaa
#define ACH_NPU_FMAP1       0xab
#define ACL_NPU_ZPAD        0xac
#define ACH_NPU_ZPAD        0xad
#define ACL_NPU_IROW        0xae
#define ACH_NPU_IROW        0xaf
#define ACL_NPU_NEXT0       0xb0
#define ACH_NPU_NEXT0       0xb1
#define ACL_NPU_NEXT1       0xb2
#define ACH_NPU_NEXT1       0xb3
#define ACL_NPU_FMCROP      0xb4
#define ACH_NPU_FMCROP      0xb5
#define ACL_NPU_FMOUT       0xb6
#define ACH_NPU_FMOUT       0xb7

#define ACL_NPU_US          0xb8
#define ACH_NPU_US          0xb9
#define ACL_NPU_HUS         0xba
#define ACH_NPU_HUS         0xbb
#define ACL_NPU_VUS         0xbc
#define ACH_NPU_VUS         0xbd
#define ACL_NPU_PCONV       0xbe
#define ACH_NPU_PCONV       0xbf
#define ACL_NPU_TRIM        0xc0
#define ACH_NPU_TRIM        0xc1
#define ACL_NPU_GAP         0xc2
#define ACH_NPU_GAP         0xc3
#define ACL_NPU_RELU        0xc4
#define ACH_NPU_RELU        0xc5
#define ACL_NPU_RELU6       0xc6
#define ACH_NPU_RELU6       0xc7
#define ACL_NPU_PFUNC       0xc8
#define ACH_NPU_PFUNC       0xc9
#define ACL_NPU_PFMAP0      0xca
#define ACH_NPU_PFMAP0      0xcb
#define ACL_NPU_PFMAP1      0xcc
#define ACH_NPU_PFMAP1      0xcd
#define ACL_NPU_PZPAD       0xce
#define ACH_NPU_PZPAD       0xcf
#define ACL_NPU_PIROW       0xd0
#define ACH_NPU_PIROW       0xd1
#define ACL_NPU_PNEXT0      0xd2
#define ACH_NPU_PNEXT0      0xd3
#define ACL_NPU_PNEXT1      0xd4
#define ACH_NPU_PNEXT1      0xd5
#define ACL_NPU_PFMCROP     0xd6
#define ACH_NPU_PFMCROP     0xd7
#define ACL_NPU_PFMOUT      0xd8
#define ACH_NPU_PFMOUT      0xd9
#define ACL_NPU_POOL        0xda
#define ACH_NPU_POOL        0xdb
#define ACL_NPU_PAT         0xdc
#define ACH_NPU_PAT         0xdd
#define ACL_NPU_CC0         0xde
#define ACH_NPU_CC0         0xdf
#define ACL_NPU_CC1         0xe0
#define ACH_NPU_CC1         0xe1
#define ACL_NPU_CC2         0xe2
#define ACH_NPU_CC2         0xe3
#define ACL_NPU_CC3         0xe4
#define ACH_NPU_CC3         0xe5
#define ACL_NPU_CC4         0xe6
#define ACH_NPU_CC4         0xe7
#define ACL_NPU_CC5         0xe8
#define ACH_NPU_CC5         0xe9
#define ACL_NPU_FORMAT      0xea
#define ACH_NPU_FORMAT      0xeb
#define ACL_NPU_RESIZE      0xec
#define ACH_NPU_RESIZE      0xed
#define ACL_NPU_RESIZE_SRC  0xee
#define ACH_NPU_RESIZE_SRC  0xef
#define ACL_NPU_RESIZE_DST  0xf0
#define ACH_NPU_RESIZE_DST  0xf1
#define ACL_NPU_RESIZE_INIT0 0xf2
#define ACH_NPU_RESIZE_INIT0 0xf3
#define ACL_NPU_RESIZE_INIT1 0xf4
#define ACH_NPU_RESIZE_INIT1 0xf5
#define ACL_NPU_RESIZE_RATIO0 0xf6
#define ACH_NPU_RESIZE_RATIO0 0xf7
#define ACL_NPU_RESIZE_RATIO1 0xf8
#define ACH_NPU_RESIZE_RATIO1 0xf9
#define ACL_NPU_CHAN        0xfa
#define ACH_NPU_CHAN        0xfb
#define ACL_NPU_PREP0       0xfc
#define ACH_NPU_PREP0       0xfd
#define ACL_NPU_PREP1       0xfe
#define ACH_NPU_PREP1       0xff
#define ACL_NPU_PREP2       0x100
#define ACH_NPU_PREP2       0x101
#define ACL_NPU_PREP3       0x102
#define ACH_NPU_PREP3       0x103

#define NPU_CODE_a(x)                   (((x)&0xffffffff)<<0)
#define NPU_CLEN_l(x)                   (((x)&0xfffff)<<0)
#define NPU_RUN_pfunc(x)                (((x)&0x1)<<24)
#define NPU_RUN_conv(x)                 (((x)&0x1)<<23)
#define NPU_RUN_getw(x)                 (((x)&0x1)<<22)
#define NPU_RUN_wdma(x)                 (((x)&0x1)<<21)
#define NPU_RUN_rdma(x)                 (((x)&0x1)<<20)
#define NPU_RUN_wfc(x)                  (((x)&0x1)<<17)
#define NPU_RUN_busy(x)                 (((x)&0x1)<<16)
#define NPU_RUN_conti(x)                (((x)&0x1)<<1)
#define NPU_RUN_go(x)                   (((x)&0x1)<<0)
#define NPU_ELEN_l(x)                   (((x)&0xfffff)<<0)
#define NPU_VER_num(x)                  (((x)&0xffff)<<0)
#define NPU_MACRO_sd(x)                 (((x)&0x1)<<0)
#define NPU_DMA_we(x)                   (((x)&0x1)<<31)
#define NPU_DMA_sel_pri(x)              (((x)&0x1)<<30)
#define NPU_DMA_sel_grp(x)              (((x)&0x1)<<29)
#define NPU_DMA_pri(x)                  (((x)&0x7)<<26)
#define NPU_DMA_grp(x)                  (((x)&0x3)<<24)
#define NPU_DMA_idx(x)                  (((x)&0x3)<<22)
#define NPU_DMA_lck_inst(x)             (((x)&0x1)<<21)
#define NPU_DMA_lck_getw(x)             (((x)&0x1)<<20)
#define NPU_DMA_lck_rdma(x)             (((x)&0x1)<<19)
#define NPU_DMA_bl(x)                   (((x)&0x1ff)<<0)
#define NPU_DMAFT_en(x)                 (((x)&0x1)<<0)
#define NPU_RDMA0_SRC0_sa(x)            (((x)&0xffffff)<<0)
#define NPU_RDMA0_SRC1_pitch_l(x)       (((x)&0xffffff)<<0)
#define NPU_RDMA0_SRC2_pitch_c(x)       (((x)&0xffffff)<<0)
#define NPU_RDMA0_SRC3_len(x)           (((x)&0xffff)<<0)
#define NPU_RDMA0_SRC4_base(x)          (((x)&0xffffffff)<<0)
#define NPU_RDMA0_DST_dm(x)             (((x)&0xf)<<28)
#define NPU_RDMA0_DST_dl(x)             (((x)&0xfffff)<<0)
#define NPU_RDMA0_BLK0_ch(x)            (((x)&0xffff)<<16)
#define NPU_RDMA0_BLK0_line_c(x)        (((x)&0xffff)<<0)
#define NPU_RDMA0_BLK1_line(x)          (((x)&0xffff)<<0)
#define NPU_RDMA1_SRC0_sa(x)            (((x)&0xffffff)<<0)
#define NPU_RDMA1_SRC1_pitch_l(x)       (((x)&0xffffff)<<0)
#define NPU_RDMA1_SRC2_pitch_c(x)       (((x)&0xffffff)<<0)
#define NPU_RDMA1_SRC3_len(x)           (((x)&0xffff)<<0)
#define NPU_RDMA1_SRC4_base(x)          (((x)&0xffffffff)<<0)
#define NPU_RDMA1_DST_dm(x)             (((x)&0xf)<<28)
#define NPU_RDMA1_DST_dl(x)             (((x)&0xfffff)<<0)
#define NPU_RDMA1_BLK0_ch(x)            (((x)&0xffff)<<16)
#define NPU_RDMA1_BLK0_line_c(x)        (((x)&0xffff)<<0)
#define NPU_RDMA1_BLK1_line(x)          (((x)&0xffff)<<0)
#define NPU_RDMA2_SRC0_sa(x)            (((x)&0xffffff)<<0)
#define NPU_RDMA2_SRC1_pitch_l(x)       (((x)&0xffffff)<<0)
#define NPU_RDMA2_SRC2_pitch_c(x)       (((x)&0xffffff)<<0)
#define NPU_RDMA2_SRC3_len(x)           (((x)&0xffff)<<0)
#define NPU_RDMA2_SRC4_base(x)          (((x)&0xffffffff)<<0)
#define NPU_RDMA2_DST_dm(x)             (((x)&0xf)<<28)
#define NPU_RDMA2_DST_dl(x)             (((x)&0xfffff)<<0)
#define NPU_RDMA2_BLK0_ch(x)            (((x)&0xffff)<<16)
#define NPU_RDMA2_BLK0_line_c(x)        (((x)&0xffff)<<0)
#define NPU_RDMA2_BLK1_line(x)          (((x)&0xffff)<<0)
#define NPU_WDMA0_SRC_sm(x)             (((x)&0xf)<<28)
#define NPU_WDMA0_SRC_sl(x)             (((x)&0xfffff)<<0)
#define NPU_WDMA0_DST0_da(x)            (((x)&0xffffff)<<0)
#define NPU_WDMA0_DST1_pitch_l(x)       (((x)&0xffffff)<<0)
#define NPU_WDMA0_DST2_pitch_c(x)       (((x)&0xffffff)<<0)
#define NPU_WDMA0_DST3_len(x)           (((x)&0xffff)<<0)
#define NPU_WDMA0_DST4_base(x)          (((x)&0xffffffff)<<0)
#define NPU_WDMA0_BLK0_ch(x)            (((x)&0xffff)<<16)
#define NPU_WDMA0_BLK0_line_c(x)        (((x)&0xffff)<<0)
#define NPU_WDMA0_BLK1_line(x)          (((x)&0xffff)<<0)
#define NPU_WDMA1_SRC_sm(x)             (((x)&0xf)<<28)
#define NPU_WDMA1_SRC_sl(x)             (((x)&0xfffff)<<0)
#define NPU_WDMA1_DST0_da(x)            (((x)&0xffffff)<<0)
#define NPU_WDMA1_DST1_pitch_l(x)       (((x)&0xffffff)<<0)
#define NPU_WDMA1_DST2_pitch_c(x)       (((x)&0xffffff)<<0)
#define NPU_WDMA1_DST3_len(x)           (((x)&0xffff)<<0)
#define NPU_WDMA1_DST4_base(x)          (((x)&0xffffffff)<<0)
#define NPU_WDMA1_BLK0_ch(x)            (((x)&0xffff)<<16)
#define NPU_WDMA1_BLK0_line_c(x)        (((x)&0xffff)<<0)
#define NPU_WDMA1_BLK1_line(x)          (((x)&0xffff)<<0)
#define NPU_WDMA2_SRC_sm(x)             (((x)&0xf)<<28)
#define NPU_WDMA2_SRC_sl(x)             (((x)&0xfffff)<<0)
#define NPU_WDMA2_DST0_da(x)            (((x)&0xffffff)<<0)
#define NPU_WDMA2_DST1_pitch_l(x)       (((x)&0xffffff)<<0)
#define NPU_WDMA2_DST2_pitch_c(x)       (((x)&0xffffff)<<0)
#define NPU_WDMA2_DST3_len(x)           (((x)&0xffff)<<0)
#define NPU_WDMA2_DST4_base(x)          (((x)&0xffffffff)<<0)
#define NPU_WDMA2_BLK0_ch(x)            (((x)&0xffff)<<16)
#define NPU_WDMA2_BLK0_line_c(x)        (((x)&0xffff)<<0)
#define NPU_WDMA2_BLK1_line(x)          (((x)&0xffff)<<0)
#define NPU_NMEM_slp(x)                 (((x)&0x1)<<1)
#define NPU_NMEM_ret(x)                 (((x)&0x1)<<0)
#define NPU_NMEM_FM0_offset_x(x)        (((x)&0xffff)<<16)
#define NPU_NMEM_FM0_offset_y(x)        (((x)&0x3f)<<0)
#define NPU_NMEM_FM1_h(x)               (((x)&0xffff)<<16)
#define NPU_NMEM_FM1_w(x)               (((x)&0xffff)<<0)
#define NPU_NMEM_FM2_l(x)               (((x)&0x1)<<16)
#define NPU_NMEM_FM2_offset_s(x)        (((x)&0xf)<<4)
#define NPU_NMEM_FM2_s(x)               (((x)&0xf)<<0)
#define NPU_NMEM_PS0_offset_x(x)        (((x)&0xffff)<<16)
#define NPU_NMEM_PS0_offset_y(x)        (((x)&0x3f)<<0)
#define NPU_NMEM_PS1_h(x)               (((x)&0xffff)<<16)
#define NPU_NMEM_PS1_w(x)               (((x)&0xffff)<<0)
#define NPU_NMEM_PS2_offset_s(x)        (((x)&0xf)<<4)
#define NPU_NMEM_PS2_s(x)               (((x)&0xf)<<0)
#define NPU_NMEM_ST0_offset_x(x)        (((x)&0xffff)<<16)
#define NPU_NMEM_ST0_offset_y(x)        (((x)&0x3f)<<0)
#define NPU_NMEM_ST1_h(x)               (((x)&0xffff)<<16)
#define NPU_NMEM_ST1_w(x)               (((x)&0xffff)<<0)
#define NPU_NMEM_ST2_offset_s(x)        (((x)&0xf)<<4)
#define NPU_NMEM_ST2_s(x)               (((x)&0xf)<<0)
#define NPU_NMEM_PI0_offset_x(x)        (((x)&0xffff)<<16)
#define NPU_NMEM_PI0_offset_y(x)        (((x)&0x3f)<<0)
#define NPU_NMEM_PI1_h(x)               (((x)&0xffff)<<16)
#define NPU_NMEM_PI1_w(x)               (((x)&0xffff)<<0)
#define NPU_NMEM_PI2_offset_s(x)        (((x)&0xf)<<4)
#define NPU_NMEM_PI2_s(x)               (((x)&0xf)<<0)
#define NPU_NMEM_PO0_offset_x(x)        (((x)&0xffff)<<16)
#define NPU_NMEM_PO0_offset_y(x)        (((x)&0x3f)<<0)
#define NPU_NMEM_PO1_h(x)               (((x)&0xffff)<<16)
#define NPU_NMEM_PO1_w(x)               (((x)&0xffff)<<0)
#define NPU_NMEM_PO2_offset_s(x)        (((x)&0xf)<<4)
#define NPU_NMEM_PO2_s(x)               (((x)&0xf)<<0)
#define NPU_NMEM_RDMA0_offset_x(x)      (((x)&0xffff)<<16)
#define NPU_NMEM_RDMA0_offset_y(x)      (((x)&0x3f)<<0)
#define NPU_NMEM_RDMA1_h(x)             (((x)&0xffff)<<16)
#define NPU_NMEM_RDMA1_w(x)             (((x)&0xffff)<<0)
#define NPU_NMEM_RDMA2_offset_s(x)      (((x)&0xf)<<4)
#define NPU_NMEM_RDMA2_s(x)             (((x)&0xf)<<0)
#define NPU_NMEM_WDMA0_offset_x(x)      (((x)&0xffff)<<16)
#define NPU_NMEM_WDMA0_offset_y(x)      (((x)&0x3f)<<0)
#define NPU_NMEM_WDMA1_h(x)             (((x)&0xffff)<<16)
#define NPU_NMEM_WDMA1_w(x)             (((x)&0xffff)<<0)
#define NPU_NMEM_WDMA2_offset_s(x)      (((x)&0xf)<<4)
#define NPU_NMEM_WDMA2_s(x)             (((x)&0xf)<<0)
#define NPU_GETW0_sa(x)                 (((x)&0xfffffff)<<0)
#define NPU_GETW1_len(x)                (((x)&0xfffffff)<<0)
#define NPU_GETW2_back(x)               (((x)&0xfffff)<<0)
#define NPU_GETW3_base(x)               (((x)&0xffffffff)<<0)
#define NPU_GETW_flush(x)               (((x)&0x1)<<31)
#define NPU_GETW_decompact(x)           (((x)&0x1)<<1)
#define NPU_GETW_decompress(x)          (((x)&0x1)<<0)

#define NPU_CONV_ch_resume(x)           (((x)&0x1)<<30)
#define NPU_CONV_full_ch(x)             (((x)&0x1)<<29)
#define NPU_CONV_pformat(x)             (((x)&0x3)<<16)
#define NPU_CONV_oformat(x)             (((x)&0x1)<<12)
#define NPU_CONV_16b(x)                 (((x)&0x1)<<11)
#define NPU_CONV_acc(x)                 (((x)&0x1)<<10)
#define NPU_CONV_vstride2(x)            (((x)&0x1)<<9)
#define NPU_CONV_hstride2(x)            (((x)&0x1)<<8)
#define NPU_CONV_mode(x)                (((x)&0xff)<<0)

#define NPU_FMAP0_row(x)                (((x)&0xffff)<<16)
#define NPU_FMAP0_col(x)                (((x)&0xffff)<<0)
#define NPU_FMAP1_ch(x)                 (((x)&0xffff)<<0)
#define NPU_ZPAD_b(x)                   (((x)&0x1f)<<24)
#define NPU_ZPAD_r(x)                   (((x)&0x1f)<<16)
#define NPU_ZPAD_l(x)                   (((x)&0x1f)<<8)
#define NPU_ZPAD_t(x)                   (((x)&0x1f)<<0)
#define NPU_IROW_max(x)                 (((x)&0xf)<<0)
#define NPU_NEXT0_ch_end(x)             (((x)&0xffff)<<16)
#define NPU_NEXT0_ch_start(x)           (((x)&0xffff)<<0)
#define NPU_NEXT1_line(x)               (((x)&0xffff)<<0)
#define NPU_FMCROP_row_st(x)            (((x)&0xffff)<<16)
#define NPU_FMCROP_col_st(x)            (((x)&0xffff)<<0)
#define NPU_FMOUT_row_out(x)            (((x)&0xffff)<<16)
#define NPU_FMOUT_col_out(x)            (((x)&0xffff)<<0)
#define NPU_US_near(x)                  (((x)&0x1)<<3)
#define NPU_US_extrapo(x)               (((x)&0x1)<<2)
#define NPU_HUS_out(x)                  (((x)&0xffff)<<16)
#define NPU_HUS_delta(x)                (((x)&0xff)<<8)
#define NPU_HUS_init(x)                 (((x)&0xff)<<0)
#define NPU_VUS_line(x)                 (((x)&0xf)<<0)
#define NPU_PCONV_en(x)                 (((x)&0x1)<<31)
#define NPU_PCONV_16b(x)                (((x)&0x1)<<3)
#define NPU_PCONV_trim(x)               (((x)&0x1)<<2)
#define NPU_PCONV_gap(x)                (((x)&0x1)<<1)
#define NPU_PCONV_relu(x)               (((x)&0x1)<<0)
#define NPU_TRIM_wo(x)                  (((x)&0xf)<<24)
#define NPU_TRIM_wv(x)                  (((x)&0xf)<<20)
#define NPU_TRIM_w(x)                   (((x)&0xf)<<16)
#define NPU_TRIM_ho(x)                  (((x)&0xf)<<4)
#define NPU_TRIM_hm(x)                  (((x)&0xf)<<0)
#define NPU_GAP_col_acc(x)              (((x)&0x1)<<16)
#define NPU_GAP_mul(x)                  (((x)&0xffff)<<0)
#define NPU_RELU_mode(x)                (((x)&0x7)<<0)
#define NPU_RELU6_clamp(x)              (((x)&0xffffffff)<<0)
#define NPU_PFUNC_iformat(x)            (((x)&0xf)<<12)
#define NPU_PFUNC_oformat(x)            (((x)&0xf)<<8)
#define NPU_PFUNC_mode(x)               (((x)&0xff)<<0)
#define NPU_PFMAP0_row(x)               (((x)&0xffff)<<16)
#define NPU_PFMAP0_col(x)               (((x)&0xffff)<<0)
#define NPU_PFMAP1_ch(x)                (((x)&0xffff)<<0)
#define NPU_PZPAD_b(x)                  (((x)&0x1f)<<24)
#define NPU_PZPAD_r(x)                  (((x)&0x1f)<<16)
#define NPU_PZPAD_l(x)                  (((x)&0x1f)<<8)
#define NPU_PZPAD_t(x)                  (((x)&0x1f)<<0)
#define NPU_PIROW_max(x)                (((x)&0xf)<<0)
#define NPU_PNEXT0_ch_end(x)            (((x)&0xffff)<<16)
#define NPU_PNEXT0_ch_start(x)          (((x)&0xffff)<<0)
#define NPU_PNEXT1_line(x)              (((x)&0xffff)<<0)
#define NPU_PFMCROP_row_st(x)           (((x)&0xffff)<<16)
#define NPU_PFMCROP_col_st(x)           (((x)&0xffff)<<0)
#define NPU_PFMOUT_row_out(x)           (((x)&0xffff)<<16)
#define NPU_PFMOUT_col_out(x)           (((x)&0xffff)<<0)

#define NPU_POOL_row_cnt(x)             (((x)&0xf)<<28)
#define NPU_POOL_row(x)                 (((x)&0xf)<<24)
#define NPU_POOL_col_cnt(x)             (((x)&0xf)<<20)
#define NPU_POOL_col(x)                 (((x)&0xf)<<16)
#define NPU_POOL_op(x)                  (((x)&0x3)<<4)
#define NPU_POOL_mode(x)                (((x)&0xf)<<0)

#define NPU_PAT_c(x)                    (((x)&0xffffffff)<<0)
#define NPU_CC0_c01(x)                  (((x)&0xffff)<<16)
#define NPU_CC0_c00(x)                  (((x)&0xffff)<<0)
#define NPU_CC1_b0(x)                   (((x)&0xffff)<<16)
#define NPU_CC1_c02(x)                  (((x)&0xffff)<<0)
#define NPU_CC2_c11(x)                  (((x)&0xffff)<<16)
#define NPU_CC2_c10(x)                  (((x)&0xffff)<<0)
#define NPU_CC3_b1(x)                   (((x)&0xffff)<<16)
#define NPU_CC3_c12(x)                  (((x)&0xffff)<<0)
#define NPU_CC4_c21(x)                  (((x)&0xffff)<<16)
#define NPU_CC4_c20(x)                  (((x)&0xffff)<<0)
#define NPU_CC5_b2(x)                   (((x)&0xffff)<<16)
#define NPU_CC5_c22(x)                  (((x)&0xffff)<<0)

#define NPU_FORMAT_en(x)                (((x)&0x1)<<31)
#define NPU_FORMAT_smode(x)             (((x)&0xf)<<12)
#define NPU_FORMAT_uv_sub_128(x)        (((x)&0x1)<<9)
#define NPU_FORMAT_y_sub_128(x)         (((x)&0x1)<<8)
#define NPU_FORMAT_mode(x)              (((x)&0xff)<<0)
#define NPU_RESIZE_en(x)                (((x)&0x1)<<31)
#define NPU_RESIZE_restart(x)           (((x)&0x1)<<30)
#define NPU_RESIZE_SRC_offset(x)        (((x)&0xf)<<0)
#define NPU_RESIZE_DST_h(x)             (((x)&0x7ff)<<16)
#define NPU_RESIZE_DST_w(x)             (((x)&0x7ff)<<0)
#define NPU_RESIZE_INIT0_w(x)           (((x)&0x1fffff)<<0)
#define NPU_RESIZE_INIT1_h(x)           (((x)&0x1fffff)<<0)
#define NPU_RESIZE_RATIO0_w(x)          (((x)&0xfffff)<<0)
#define NPU_RESIZE_RATIO1_h(x)          (((x)&0xfffff)<<0)
#define NPU_CHAN_en(x)                  (((x)&0x1)<<31)
#define NPU_CHAN_c1(x)                  (((x)&0x1)<<0)
#define NPU_PREP0_sub(x)                (((x)&0xffff)<<16)
#define NPU_PREP1_pad_r(x)              (((x)&0xff)<<24)
#define NPU_PREP1_pad_l(x)              (((x)&0xff)<<16)
#define NPU_PREP1_pad_b(x)              (((x)&0xff)<<8)
#define NPU_PREP1_pad_t(x)              (((x)&0xff)<<0)
#define NPU_PREP2_shift(x)              (((x)&0xf)<<0)
#define NPU_PREP3_pad(x)                (((x)&0xffffffff)<<0)
#define NPU_ENCRYPT_wt(x)               (((x)&0x1)<<1)
#define NPU_ENCRYPT_inst(x)             (((x)&0x1)<<0)
#define NPU_KEY_k(x)                    (((x)&0xffffffff)<<0)
#define NPU_INTEN_err_inst(x)           (((x)&0x1)<<11)
#define NPU_INTEN_err_wt(x)             (((x)&0x1)<<10)
#define NPU_INTEN_err_config(x)         (((x)&0x1)<<9)
#define NPU_INTEN_err_axi(x)            (((x)&0x1)<<8)
#define NPU_INTEN_int(x)                (((x)&0xff)<<0)
#define NPU_INT_err_inst(x)             (((x)&0x1)<<11)
#define NPU_INT_err_wt(x)               (((x)&0x1)<<10)
#define NPU_INT_err_config(x)           (((x)&0x1)<<9)
#define NPU_INT_err_axi(x)              (((x)&0x1)<<8)
#define NPU_INT_int(x)                  (((x)&0xff)<<0)
#define NPU_DBG0_m(x)                   (((x)&0xff)<<0)
#define NPU_DBG1_v(x)                   (((x)&0xffffffff)<<0)
#define NPU_DBG2_step(x)                (((x)&0x1)<<0)
#define NPU_REGM_c(x)                   (((x)&0xffffffff)<<0)
#define NPU_DUMMY_0_b(x)                (((x)&0xffffffff)<<0)
#define NPU_DUMMY_1_b(x)                (((x)&0xffffffff)<<0)
#define NPU_DUMMY_2_b(x)                (((x)&0xffffffff)<<0)
